
# local imports
from patch import *
from img_load import load_training
from img_manipulation import binarize_imgs

from modelUNET_120 import get_unet_120,f1_score

# librairies imports
import numpy as np
import matplotlib.pyplot as plt
import pickle
import tensorflow as tf
from keras.models import *
from keras.layers import *
from keras.regularizers import *
from keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau
from keras.optimizers import Adam

file = open("UNET_patch_120_Dropout_0.1_Ker_1.history",'rb')
hist_01_1 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.2_Ker_1.history",'rb')
hist_02_1 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.3_Ker_1.history",'rb')
hist_03_1 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.4_Ker_1.history",'rb')
hist_04_1 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.5_Ker_1.history",'rb')
hist_05_1 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.6_Ker_1.history",'rb')
hist_06_1 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.7_Ker_1.history",'rb')
hist_07_1 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.8_Ker_1.history",'rb')
hist_08_1 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.9_Ker_1.history",'rb')
hist_09_1 = pickle.load(file)
file.close()

file = open("UNET_patch_120_Dropout_0.1_Ker_2.history",'rb')
hist_01_2 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.2_Ker_2.history",'rb')
hist_02_2 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.3_Ker_2.history",'rb')
hist_03_2 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.4_Ker_2.history",'rb')
hist_04_2 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.5_Ker_2.history",'rb')
hist_05_2 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.6_Ker_2.history",'rb')
hist_06_2 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.7_Ker_2.history",'rb')
hist_07_2 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.8_Ker_2.history",'rb')
hist_08_2 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.9_Ker_2.history",'rb')
hist_09_2 = pickle.load(file)
file.close()

file = open("../Dropout/UNET_patch_120_0.1_.history",'rb')
hist_01_3 = pickle.load(file)
file.close()
file = open("../Dropout/UNET_patch_120_0.2_.history",'rb')
hist_02_3 = pickle.load(file)
file.close()
file = open("../Dropout/UNET_patch_120_0.3_.history",'rb')
hist_03_3 = pickle.load(file)
file.close()
file = open("../Dropout/UNET_patch_120_0.4_.history",'rb')
hist_04_3 = pickle.load(file)
file.close()
file = open("../Dropout/UNET_patch_120_0.5_.history",'rb')
hist_05_3 = pickle.load(file)
file.close()
file = open("../Dropout/UNET_patch_120_0.6_.history",'rb')
hist_06_3 = pickle.load(file)
file.close()
file = open("../Dropout/UNET_patch_120_0.7_.history",'rb')
hist_07_3 = pickle.load(file)
file.close()
file = open("../Dropout/UNET_patch_120_0.8_.history",'rb')
hist_08_3 = pickle.load(file)
file.close()
file = open("../Dropout/UNET_patch_120_0.9_.history",'rb')
hist_09_3 = pickle.load(file)
file.close()

file = open("UNET_patch_120_Dropout_0.1_Ker_4.history",'rb')
hist_01_4 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.2_Ker_4.history",'rb')
hist_02_4 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.3_Ker_4.history",'rb')
hist_03_4 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.4_Ker_4.history",'rb')
hist_04_4 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.5_Ker_4.history",'rb')
hist_05_4 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.6_Ker_4.history",'rb')
hist_06_4 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.7_Ker_4.history",'rb')
hist_07_4 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.8_Ker_4.history",'rb')
hist_08_4 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.9_Ker_4.history",'rb')
hist_09_4 = pickle.load(file)
file.close()

file = open("UNET_patch_120_Dropout_0.1_Ker_5.history",'rb')
hist_01_5 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.2_Ker_5.history",'rb')
hist_02_5 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.3_Ker_5.history",'rb')
hist_03_5 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.4_Ker_5.history",'rb')
hist_04_5 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.5_Ker_5.history",'rb')
hist_05_5 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.6_Ker_5.history",'rb')
hist_06_5 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.7_Ker_5.history",'rb')
hist_07_5 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.8_Ker_5.history",'rb')
hist_08_5 = pickle.load(file)
file.close()
file = open("UNET_patch_120_Dropout_0.9_Ker_5.history",'rb')
hist_09_5 = pickle.load(file)
file.close()

fig_Ker1, ax_Ker1 = plt.subplots( nrows=1, ncols=1 )  # create figure & 1 axis
model_01_Ker1, = ax_Ker1.plot(hist_01['val_f1_score'], label='0.1')
model_02_Ker1, = ax_Ker1.plot(hist_02['val_f1_score'], label='0.2')
model_03_Ker1, = ax_Ker1.plot(hist_03['val_f1_score'], label='0.3')
model_04_Ker1, = ax_Ker1.plot(hist_04['val_f1_score'], label='0.4')
model_05_Ker1, = ax_Ker1.plot(hist_05['val_f1_score'], label='0.5')
model_06_Ker1, = ax_Ker1.plot(hist_06['val_f1_score'], label='0.6')
model_07_Ker1, = ax_Ker1.plot(hist_07['val_f1_score'], label='0.7')
model_08_Ker1, = ax_Ker1.plot(hist_08['val_f1_score'], label='0.8')
model_09_Ker1, = ax_Ker1.plot(hist_09['val_f1_score'], label='0.9')
plt.ylabel('F1 score')
plt.xlabel('Epochs')
plt.legend(handles=[model_01,model_02,model_03,model_04,model_05,model_06,model_07,model_08,model_09])
plt.show()
fig.savefig('dropout_f1.pdf', bbox_inches='tight')   # save the figure to file
plt.close(fig)

fig2, ax2 = plt.subplots( nrows=1, ncols=1 )  # create figure & 1 axis
model_01, = ax2.plot(hist_01['val_acc'], label='0.1')
model_02, = ax2.plot(hist_02['val_acc'], label='0.2')
model_03, = ax2.plot(hist_03['val_acc'], label='0.3')
model_04, = ax2.plot(hist_04['val_acc'], label='0.4')
model_05, = ax2.plot(hist_05['val_acc'], label='0.5')
model_06, = ax2.plot(hist_06['val_acc'], label='0.6')
model_07, = ax2.plot(hist_07['val_acc'], label='0.7')
model_08, = ax2.plot(hist_08['val_acc'], label='0.8')
model_09, = ax2.plot(hist_09['val_acc'], label='0.9')
plt.ylabel('Accuracy')
plt.xlabel('Epochs')
plt.legend(handles=[model_01,model_02,model_03,model_04,model_05,model_06,model_07,model_08,model_09])
plt.show()
fig2.savefig('dropout_acc.pdf', bbox_inches='tight')   # save the figure to file
plt.close(fig2)

fig3, ax3 = plt.subplots( nrows=1, ncols=1 )  # create figure & 1 axis
model_01, = ax3.plot(hist_01['val_loss'], label='0.1')
model_02, = ax3.plot(hist_02['val_loss'], label='0.2')
model_03, = ax3.plot(hist_03['val_loss'], label='0.3')
model_04, = ax3.plot(hist_04['val_loss'], label='0.4')
model_05, = ax3.plot(hist_05['val_loss'], label='0.5')
model_06, = ax3.plot(hist_06['val_loss'], label='0.6')
model_07, = ax3.plot(hist_07['val_loss'], label='0.7')
model_08, = ax3.plot(hist_08['val_loss'], label='0.8')
model_09, = ax3.plot(hist_09['val_loss'], label='0.9')
plt.ylabel('Loss')
plt.xlabel('Epochs')
plt.legend(handles=[model_01,model_02,model_03,model_04,model_05,model_06,model_07,model_08,model_09])
plt.show()
fig3.savefig('dropout_loss.pdf', bbox_inches='tight')   # save the figure to file
plt.close(fig3)
